---

name: Infrastructure Agent Linux Installer
description: New Relic install recipe for the Infrastructure agent
repository: https://github.com/newrelic/infrastructure-agent

# See http://download.newrelic.com/infrastructure_agent/ for possible permutations of platform/arch
platform: linux
arch: "386"

# Still TBD
# Some variable/indicator for where you're trying to install this that isn't necessarily where you're running the newrelic-cli from
# Options - native, vm, docker, kubernetes, serverless/lambda, prometheus-exporter etc.
target_environment: vm

# Examine Infrastructure events for correlated data
process_match:
  - /infra/

# Examine Metrics, Events, and Logging for correlated data
# Used by the UI to determine if you've successfully configured and are ingesting data
melt_match:
  events:
    - pattern: /SystemSample/
  metrics:
    - pattern: /system.cpu.usage/
  logging:
    - pattern: /http/
      files:
        - /var\/log\/system.log

install:
  # go-task yaml definition goes here
  # This spec - https://github.com/go-task/task

  version: "3"

  variables:
    - FOO_VAR: foo-value

  tasks:
    install:
      cmds:
        - task: setup_nr_profile
        - task: install_infra

    setup_nr_profile:
      cmds:
        - echo "Setting up NR Profile"

    install_infra:
      cmds:
        - echo "Installing the Infrastructure agent"
        - curl -L https://raw.githubusercontent.com/fryckbos/infra-install/master/install.sh {{.NR_LICENSE_KEY}} | sh
      silent: true
