name: Tutone Generate
on:
  push:
    branches: [master]
  schedule:
    - cron: "5 5 * * 1"

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    container: golang:1.15-buster
    steps:
      - uses: actions/checkout@v2

      - name: Set up git user
        run: |
          git config --global user.name nr-developer-toolkit
          git config --global user.email nr-developer-toolkit@users.noreply.github.com

      - name: Generate new code
        run: make generate
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.DEV_TOOLKIT_TOKEN }}
          commit-message: "chore(tutone): update generated code"
          signoff: false
          branch: tutone-updates
          title: "chore(tutone): update generated code"
          body: |
            Update generated code using tutone
            - make generate
            - PR generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            enhancement
          draft: false

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
